// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjnyx_Pqqek3n8_g_VrN_PRHzXp4nUKUc',
    appId: '1:814660781162:web:36f2ad6bcdbb5f6967f613',
    messagingSenderId: '814660781162',
    projectId: 'nafi3-9805b',
    authDomain: 'nafi3-9805b.firebaseapp.com',
    storageBucket: 'nafi3-9805b.firebasestorage.app',
    measurementId: 'G-65SG28REW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2iH92S_B-iSK_T_aHDSRIF4xSrEgEOSs',
    appId: '1:814660781162:android:d29785693971391a67f613',
    messagingSenderId: '814660781162',
    projectId: 'nafi3-9805b',
    storageBucket: 'nafi3-9805b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjnyx_Pqqek3n8_g_VrN_PRHzXp4nUKUc',
    appId: '1:814660781162:web:74aa3558c80fdb6e67f613',
    messagingSenderId: '814660781162',
    projectId: 'nafi3-9805b',
    authDomain: 'nafi3-9805b.firebaseapp.com',
    storageBucket: 'nafi3-9805b.firebasestorage.app',
    measurementId: 'G-S9WNXG5JT1',
  );
}
