// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVJ_OTWVXcBWQcH2MPB-x8oxCY_h3QIZE',
    appId: '1:31891669250:web:ddfd35e0ee2a1b1f56821b',
    messagingSenderId: '31891669250',
    projectId: 'nafi3-fa1e5',
    authDomain: 'nafi3-fa1e5.firebaseapp.com',
    storageBucket: 'nafi3-fa1e5.firebasestorage.app',
    measurementId: 'G-2VN66X9DJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVKZQK210JU8Sfgv8KFBBVE68ORcyas9I',
    appId: '1:31891669250:android:19c808f3c02d8ab756821b',
    messagingSenderId: '31891669250',
    projectId: 'nafi3-fa1e5',
    storageBucket: 'nafi3-fa1e5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVJ_OTWVXcBWQcH2MPB-x8oxCY_h3QIZE',
    appId: '1:31891669250:web:63f22c35af1f5be356821b',
    messagingSenderId: '31891669250',
    projectId: 'nafi3-fa1e5',
    authDomain: 'nafi3-fa1e5.firebaseapp.com',
    storageBucket: 'nafi3-fa1e5.firebasestorage.app',
    measurementId: 'G-5WNB9YBPVK',
  );
}
